language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - node_modules
env:
- EMBER_TRY_SCENARIO=default
- EMBER_TRY_SCENARIO=ember-release
- EMBER_TRY_SCENARIO=ember-beta
- EMBER_TRY_SCENARIO=ember-canary
matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-canary
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
deploy:
  provider: npm
  email: null@affinitygamescollective.org
  api_key:
    secure: 3qYw9sIZU0iWAOQCJIgNWlIRbV41hHkzGDopv++0+pZ6PTd900yOgar0YoB1jq8hiVgxuSoI/wfBIaaDGoxKLPNfmIkgK3AzUo8CBjwfkZuGHHBls06wIycy7wxE5jz/Dnj2t2hf09olfVWlz/3l0u6nq3Cf5UbOoIv5RPjcV4ZjGRu/kiRowvP0wK4MhZMkA2gqkLvjEKe5g6AH6kjABIN6srtyljMpwBrJ/UwZwOhyJs7KluKm/5rgUykrwtJHLKtBBPigViJwjBUen2mjD+f1oN34wa0nCdJOBqjgxCr3UaxM72Kv+HHjyF4X1Unp0TBVaG3PCTsnVxVvSecWUwC2Xcdl2EUAtWhu4jqHk/xyI8LY8zwKqseGN83UKs0ZaKXp3H1cR4TZdk3sEq/jX/ZQ+7wykTTMiMRkqOi+o7RL+ON0lpFpI2RfNEuI5hTNONVNqgNHiNbFdTOn4mNswwDGOcM4tNMZhv9/+RyV+2oUWu6FG9+pzm1/NCjuT0NSJ+A+D+CcF6QAHRDOLW5oHtA9L9N5Iy320Sw6a957NB+of5SeemIV50LC/V+sB6q7DmGiArr/4MJtu49Eag67ogZzpTp5JiDSok8wzZtMJeYfrtnBgEzl/nmpuaY0Hxvld5AGImqwcNHNXp7qsAx8dKLDCART4dMbbjYKyMSkF4o=
  on:
    tags: true
    repo: null-null-null/ember-progress-bar
